CONNECT C##MYUSER/mypassword;     
create table TRANSACTIONS (
          id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
          amount INTEGER,
          account_type_origin VARCHAR(50),
          id_origin NUMBER(10),
          account_type_destination VARCHAR(50),
          id_destination NUMBER(10),
          create_ts timestamp DEFAULT CURRENT_TIMESTAMP ,
          update_ts timestamp
     );
CREATE OR REPLACE TRIGGER TRG_TRANSACTIONS_UPD
BEFORE INSERT OR UPDATE ON TRANSACTIONS
REFERENCING NEW AS NEW_ROW
FOR EACH ROW
BEGIN
SELECT SYSDATE
     INTO :NEW_ROW.UPDATE_TS
     FROM DUAL;
END;
begin
  while 1 = 1
  loop
    insert into TRANSACTIONS (amount,account_type_origin,id_origin,account_type_destination,id_destination) 
    values(dbms_random.Value(1,500000),
    CASE round(dbms_random.value(1,4)) 
            WHEN 1 THEN 'Euros' 
            WHEN 2 THEN 'Dollars' 
            WHEN 3 THEN 'Yen' 
            WHEN 4 THEN 'Pesos' 
     END,
     round(dbms_random.value(1,5)),
     CASE round(dbms_random.value(1,4)) 
            WHEN 1 THEN 'Euros' 
            WHEN 2 THEN 'Dollars' 
            WHEN 3 THEN 'Yen' 
            WHEN 4 THEN 'Pesos' 
     END,
     round(dbms_random.value(1,5)));
     commit;
    dbms_lock.sleep(round(dbms_random.value(1,5)));
    commit;
  end loop;   
end;